services:
    eb78_router_subscriber:
        class: EB78\CustomI18nRouterBundle\Subscriber\RouterSubscriber
        arguments:
            - '@service_container'
            - '@request_stack'
        tags:
            - { name: kernel.event_subscriber }

    eb78_router_twig:
        class: EB78\CustomI18nRouterBundle\Twig\CustomRoutingExtension
        arguments:
            - '@service_container'
            - '@request_stack'
            - '@router'
        tags:
            - { name: twig.extension }

    eb78_router_command:
        class: EB78\CustomI18nRouterBundle\Command\RouterCommand
        arguments:
            - '@service_container'
        tags:
            - { name: console.command }